theme: jekyll-theme-leap-day
title: Sourya Dey
email: souryade@usc.edu
description: Site under construction, ignore all content for now!!
baseurl: ""
url: "https://souryadey.github.io"
github_username:  souryadey

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

timezone: America/Los_Angeles
