theme: 
title: Sourya Dey
email: souryade@usc.edu
description: Feel free to bookmark this page to get updates about me
baseurl: ""
url: "https://souryadey.github.io"
github_username:  souryadey

theme: jekyll-theme-minimal

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

timezone: America/Los_Angeles
