theme: jekyll-theme-minimal
markdown: kramdown

title: Sourya Dey
name: Sourya Dey
email: sourya.dey@gmail.com
description: Sourya Dey's personal website
url: "https://souryadey.github.io"
github_username: souryadey
timezone: America/New_York

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      author: "Sourya Dey"