theme: jekyll-theme-leap-day
markdown: kramdown

name: Sourya Dey
email: souryade@usc.edu
description: Site under construction, ignore all content for now!!
url: "https://souryadey.github.io"
github_username:  souryadey
timezone: America/Los_Angeles

defaults:
	-
		scope:
			path: ""
			type: "posts"
		values:
			layout: "default"
			author: "Sourya Dey"
